version: '2'
services:
  app:
    build: .
    image: jessicagreben/greben
    ports:
    - "8080:8080"
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes: 
    - /data/db
